version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform init -lock=false -force-copy -input=false
      - terraform apply -auto-approve -input=false

      # ECS Destroy
      #- terraform init -force-copy -input=false
      #- terraform destroy -lock=false -auto-approve -input=false
